### ISSUE TITLE
Pastes to RTF/ANSI Escape Codes?

### ISSUE THREAD

**Issue by sparty02** [atian25/vscode-copy-syntax#1]
This doesn't seem to work at all for me.  I copied the following:

![image](https://cloud.githubusercontent.com/assets/1483538/18837225/99e299ce-83c8-11e6-9f4c-be004dab0392.png)

And pasted it into several different programs, all consistently showing the following:

![image](https://cloud.githubusercontent.com/assets/1483538/18837234/a25c56f8-83c8-11e6-8f1e-0b429e320e7f.png)

...which looks like some kind of RTF/ANSI escape codes maybe?  FWIW, I'm on Windows 7.

**Comment by atian25** [comment]
yes, it convert code to RTF. 

sorry I don't have windows now, I will try to find one tomorrow.

**Comment by atian25** [comment]
maybe it's the problem of [copy-paste](https://github.com/xavi-/node-copy-paste) module

**Comment by atian25** [comment]
@sparty02 had try at windows.  
- `pygmentize` convert code to rtf work fine.
- the rtf string can be save to `test.rtf` file, then open it with word, can found is highlighted.
- the problem is `copy-paste` can't set clipboard with rtf format
- so I raise an issue,  https://github.com/xavi-/node-copy-paste/issues/52

**Comment by brightloudnoise** [comment]
I don't think it's an issue with the node-copy-paste.

Based on what I've read on how [Windows clipboard works](https://msdn.microsoft.com/en-us/library/windows/desktop/ms649012(v=vs.85).aspx). You need to specify RTF or a custom format as part of the copy action.

node-copy-paste relies on clip.exe, which is provided with Windows, and only passes pure text.

**Comment by brightloudnoise** [comment]
I commented on https://github.com/xavi-/node-copy-paste/issues/52 with an experiment that may provide us a path forward.

**Comment by atian25** [comment]
@brightloudnoise great~  so could you raise a PR for it ? or just fork to publish another lib (cause `node-copy-paste` seams to be not maintenance)

**Comment by shivan** [comment]
same as https://github.com/atian25/vscode-copy-syntax/issues/6
Now with vscode 1.10 it supports copy syntax without extra plugin.
