### ISSUE TITLE
Copies to a size half of designated fontsize

### ISSUE THREAD

**Issue by jakepeyser** [atian25/vscode-copy-syntax#2]
When I use the extension to copy code to RTF, it gets pasted at half the size of the 'fontsize' I have specified in my user settings. For instance, I have these settings

``` json
"copy-syntax.formatters.rtf": {
        "style": "default",
        "fontsize": 20,
        "fontface": "Menlo"
    }
```

and it gets pasted in other applications at size 10, regardless of the application. This happens for the default-settings and other `fontfaces` as well.

**Comment by atian25** [comment]
yes, it is pygments param,. half size, thanks for report, I will add doc for it.

**Comment by atian25** [comment]
closed by https://github.com/atian25/vscode-copy-syntax/commit/5f7546af94491fe6b80d06c07f88438d64b7dfb6

publish 0.4.2
