### ISSUE TITLE
Syntax copying doesn't respect theme settings

### ISSUE THREAD

**Issue by RualStorge** [atian25/vscode-copy-syntax#3]
While this might be a limitation of the extension's ability to access vs code settings or arguably a feature request when you copy code from vscode you're expecting it to more or less look like what you see in your code editor, however; when you `Copy Syntax` the font size, type, and colors all change requiring you to adjust / correct code highlighting. It would really improve this extension if it were able to utilize the currently loaded theme. (at least color, font size and type are easy as just select all and change, but color is painful to adjust)

**Comment by atian25** [comment]
sorry, I'm not familiar with theme, and after some dig, can't found any api to get vscode's current theme name.

PR is welcome.

**Comment by atian25** [comment]
1. if we know the theme name
2. then can use `vscode.extensions.getExtension('vscode.theme-xxx')` to get the config
3. then read the `json` or `xml` to find color config
4. then transform to `pygmentize` style

now step 1 is trouble, but sorry again I'm not good at the style job(step 4)... 
so PR is welcome.

**Comment by RualStorge** [comment]
no problem, I can try looking into this when I get a chance. I think the biggest challenge will be to set this up to access what theme is currently in use. step 2 and 3 should be easy enough, step 4 will be the time sink of just figuring through it. I'll take a look and when I can put something together send you a PR (might be a little bit due to this week specifically being hectic for me)

**Comment by atian25** [comment]
https://code.visualstudio.com/updates/v1_10#_copy-with-syntax-highlighting
