### ISSUE TITLE
Seems not to work on Windows (10)?

### ISSUE THREAD

**Issue by shivan** [atian25/vscode-copy-syntax#6]
On Windows it copies something like this:

I think the clipboard-format should be set.
```
{\rtf1\ansi\uc0\deff0{\fonttbl{\f0\fmodern\fprq1\fcharset0 Monaco;}}{\colortbl;\red187\green187\blue187;\red64\green128\blue128;\red188\green122\blue0;\red0\green128\blue0;\red176\green0\blue64;\red102\green102\blue102;\red170\green34\blue255;\red0\green0\blue255;\red210\green65\blue58;\red25\green23\blue124;\red136\green0\blue0;\red160\green160\blue0;\red153\green153\blue153;\red125\green144\blue41;\red186\green33\blue33;\red187\green102\blue136;\red187\green102\blue34;\red0\green0\blue128;\red128\green0\blue128;\red160\green0\blue0;\red0\green160\blue0;\red255\green0\blue0;\red136\green136\blue136;\red0\green68\blue221;}\f0 \fs24            {\cf4\b <CubeGrant} {\cf14 access=}{\cf15 "all"} {\cf14 cube=}{\cf15 "Test"}{\cf4\b >}\par
}
```

see this issue:
https://github.com/xavi-/node-copy-paste/issues/52

Seems this supports  rich text:
https://www.npmjs.com/package/clipboard-js

**Comment by atian25** [comment]
yes, known  issue.
And  that  issue 52 is  raise by  me  @_@

clipboard-js  don't  support  RTF.

and  it's not  a copy  issue, but a paste issue.

**Comment by antogerva** [comment]
Do you known any third party tool to paste correctly?

**Comment by atian25** [comment]
@antogerva not yet so far

**Comment by spralle** [comment]
@antogerva Troublesome (but working) way is to open notepad, paste the result. Save as dummy.rtf and then open that document in wordpad or word or ...

**Comment by atian25** [comment]
try vscode@1.10

https://code.visualstudio.com/updates/v1_10#_copy-with-syntax-highlighting

**Comment by shivan** [comment]
Yes, the last Update 1.10 makes this plugin not neccessary anymore. The feature is built-in now.

**Comment by atian25** [comment]
@shivan had you try if it works for window? (if so, I will update README)

I will still keep it for mac keynote, because vscode build-in copy is `HTML` format, keynote only support `RTF`.

**Comment by shivan** [comment]
Hi @atian25, I tried it on windows. 

I was able to copy code and it has exactly the same colors - even the background is black!

![image](https://cloud.githubusercontent.com/assets/1827692/23558609/8f3b4c80-0034-11e7-88e0-40370ec3f48f.png)

see this in my mail program.
