### ISSUE TITLE
pygmentize: Error: no lexer for alias

### ISSUE THREAD

**Issue by antogerva** [atian25/vscode-copy-syntax#7]
Not sure if this is a Win10 issue, but I get:
```Error calling `pygmentize`: Error: no lexer for alias 'ocl' found```

I'm also using this plugin to detect OCL syntax:
https://marketplace.visualstudio.com/items?itemName=martinring.ocl#review-details

**Comment by atian25** [comment]
`pygmentize` seams don't support `ocl`
http://pygments.org/languages/
