### ISSUE TITLE
Error calling pygmentize

### ISSUE THREAD

**Issue by hellt** [atian25/vscode-copy-syntax#8]
Hi there,
installed on mac os x and trying to copy-paste JS code with a simple `copy syntax` command, but receiving the following error with no traceback present, unless I hover over the pop up.
Traceback seems to be limited for the popup, so no error statement is visible unless the `Error calling pygmentize`

How can I check the full traceback to troubleshoot what went wrong?

**Comment by atian25** [comment]
hi, this plugin will be deprecate soon, cause vscode will contain build-in support, see 
https://github.com/Microsoft/vscode/issues/3518#issuecomment-280425987

**Comment by atian25** [comment]
https://code.visualstudio.com/updates/v1_10#_copy-with-syntax-highlighting
